var num1 = 20;
var sid = 1024;
var sname = 'Smith';
var course = 'Angular 13';
var isFeePaid = true;
var duration = '30 Days';
console.log('sid', sid);
console.log('sname', sname);
console.log('course', course);
console.log('isFeePaid', isFeePaid);
console.log('duration', duration);
